language: c
dist: xenial

matrix:
 include:
    - os: linux
      env: BUILD=src
      compiler: gcc
    - os: linux
      env: BUILD=test
      compiler: gcc
    - os: linux
      env: BUILD=coverage
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --assume-yes --quiet git gcc g++ libtool autoconf; fi
script:
  - ./setup.sh &> /dev/null
  - cd code
  - make $BUILD