language: c

matrix:
 include:
    - os: linux
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --assume-yes --quiet git gcc g++ libtool autoconf; fi
script:
  - ./setup.sh
  - cd code
  - make